import { StyleSheet } from "react-native";
import Colors from "../../Shared/Colors";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#000',
    },
    backgroundImage: {
        width: '100%',
        height: '100%',
    },
    containerScroll: {
        flex: 1,
        width: '100%',
        height: 50,
        marginTop: 90,
        //backgroundColor: '#900f81',
    },
    containerInput: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        //backgroundColor: '#900f81',
        //marginTop: 40,
        //padding: 20,
    },
    textContainer: {
        width: '80%',
        height: '45%',
        //top: 20,
        //left: 10,
        margin: 15,
    },
    titleContainer: {
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        //backgroundColor: Colors.greenNeon,
        //height: '100%',
        top: 20,
        //left: 10,
        margin: 10,
    },
    text:{
        color: Colors.greenNeon,
        fontSize: 25,
        lineHeight: 45,
        textTransform: 'uppercase',
        //fontFamily: 'PoppinsExtraBold',
    },
    textModal:{
        //flexWrap: "wrap-reverse",
        color:  "#e22d36",
        fontSize: 14,
        //lineHeight: 45,
        textTransform: 'uppercase',
        justifyContent: 'center',
        alignItems: 'center',
        fontFamily: 'PoppinsExtraBold',
    },
    underlineContainer:{
        height: 50,
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 30,
        alignItems: 'center',
        margin: 2,
    },
    underline: {
        height: 1,
        width: "40%",
        backgroundColor: '#89FFDB',
        marginVertical: 10,
        alignSelf: "center",
      },
    textPrimary: {
        color: '#ffffff',
        fontSize: 25,
        //fontFamily: 'PoppinsExtraBold',
        lineHeight: 45,
        justifyContent: 'center',
        alignItems: 'center',
    },
    textSecondary: {
        color: '#89FFDB',
        fontSize: 20,
        //fontFamily: 'PoppinsRegular',
        //lineHeight: 30,
    },
    textTernary: {
        padding: 10,
        color: '#ffffff',
        fontSize: 20,
        //fontFamily: 'PoppinsExtraBold',
        //lineHeight: 30,
        left: 2,
        justifyContent: 'center',
        alignItems: 'center',
    },
});
